# Generated by Django 2.0.4 on 2018-04-12 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=100, null=True)),
                ('Prenom', models.CharField(max_length=100, null=True)),
                ('Mail', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Intervenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=100, null=True)),
                ('Prenom', models.CharField(max_length=100, null=True)),
                ('Mail', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titre', models.CharField(max_length=100)),
                ('Contenu', models.TextField(null=True)),
                ('Equipe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ApplicationEPSI.Equipe')),
                ('Intervenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ApplicationEPSI.Intervenant')),
            ],
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=100)),
                ('Intervenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ApplicationEPSI.Intervenant')),
            ],
        ),
        migrations.CreateModel(
            name='Soutien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Minutes', models.CharField(max_length=100)),
                ('Equipe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ApplicationEPSI.Equipe')),
                ('Intervenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ApplicationEPSI.Intervenant')),
                ('Projet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ApplicationEPSI.Projet')),
            ],
        ),
        migrations.AddField(
            model_name='equipe',
            name='Etudiants',
            field=models.ManyToManyField(null=True, to='ApplicationEPSI.Etudiant'),
        ),
        migrations.AddField(
            model_name='equipe',
            name='Projet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ApplicationEPSI.Projet'),
        ),
    ]
