# Generated by Django 2.0.4 on 2018-04-12 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApplicationEPSI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soutien',
            name='Projet',
        ),
        migrations.AddField(
            model_name='projet',
            name='TempsSoutien',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
