# Generated by Django 2.0.4 on 2018-04-12 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApplicationEPSI', '0002_auto_20180412_1644'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projet',
            old_name='TempsSoutien',
            new_name='TempsSoutienRestant',
        ),
    ]
